<?php

declare(strict_types=1);

namespace Zalt\Validator;

use Laminas\Validator\Digits as DigitsValidator;
use Zalt\Filter\NegativeDigits as NegativeDigitsFilter;

class NegativeDigits extends DigitsValidator
{
    public function isValid($value)
    {
        if (null === static::$filter) {
            static::$filter = new NegativeDigitsFilter();
        }

        return parent::isValid($value); // TODO: Change the autogenerated stub
    }
}